
#ifndef BIFROST_SPRITE_ANIM_API_H
#define BIFROST_SPRITE_ANIM_API_H

#ifdef BIFROSTANIMATION2D_STATIC_STATIC_DEFINE
#  define BIFROST_SPRITE_ANIM_API
#  define BIFROSTANIMATION2D_STATIC_NO_EXPORT
#else
#  ifndef BIFROST_SPRITE_ANIM_API
#    ifdef BifrostAnimation2D_static_EXPORTS
#      define BIFROST_SPRITE_ANIM_API 
#    else
#      define BIFROST_SPRITE_ANIM_API 
#    endif
#  endif

#  ifndef BIFROSTANIMATION2D_STATIC_NO_EXPORT
#    define BIFROSTANIMATION2D_STATIC_NO_EXPORT 
#  endif
#endif

#ifndef BIFROSTANIMATION2D_STATIC_DEPRECATED
#  define BIFROSTANIMATION2D_STATIC_DEPRECATED __declspec(deprecated)
#endif

#ifndef BIFROSTANIMATION2D_STATIC_DEPRECATED_EXPORT
#  define BIFROSTANIMATION2D_STATIC_DEPRECATED_EXPORT BIFROST_SPRITE_ANIM_API BIFROSTANIMATION2D_STATIC_DEPRECATED
#endif

#ifndef BIFROSTANIMATION2D_STATIC_DEPRECATED_NO_EXPORT
#  define BIFROSTANIMATION2D_STATIC_DEPRECATED_NO_EXPORT BIFROSTANIMATION2D_STATIC_NO_EXPORT BIFROSTANIMATION2D_STATIC_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef BIFROSTANIMATION2D_STATIC_NO_DEPRECATED
#    define BIFROSTANIMATION2D_STATIC_NO_DEPRECATED
#  endif
#endif

#endif /* BIFROST_SPRITE_ANIM_API_H */
